### ISSUE TITLE
 Issues with download_pfam_db and zdb setup in the db_setup workflow

### ISSUE THREAD

**Issue by ohickl** [metagenlab/zDB#144]
Hi, I ran into a couple of issues while setting up the db_setup workflow.

1.  `download_pfam_db` process:

    The workflow tried to download Pfam files from ftp://ftp.ebi.ac.uk, but the connection was refused. I updated the process to use https://ftp.ebi.ac.uk instead, and it worked fine after that. Here's the modified `download_pfam_db` process I used:

    process download_pfam_db {
        output:
            tuple path("Pfam-A.hmm"), path("Pfam-A.hmm.dat"), path("Pfam.version")

        script:
        """
        wget https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz
        wget https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.dat.gz
        wget https://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam.version.gz
        gunzip < Pfam-A.hmm.gz > Pfam-A.hmm && rm -f Pfam-A.hmm.gz
        gunzip < Pfam-A.hmm.dat.gz > Pfam-A.hmm.dat && rm -f Pfam-A.hmm.dat.gz
        gunzip < Pfam.version.gz > Pfam.version && rm -f Pfam.version.gz
        """
    }

    Just wondering: is this a known issue? Should the workflow be updated to use HTTPS by default?

2.  `zdb setup` arguments:

    I’m using zdb 1.3.4 installed via Bioconda, and I noticed that the `--amr` and `--dir` arguments don’t seem to be recognized by zdb setup, even though they’re mentioned in the help message and README. Are these arguments deprecated or just not supported in this version?

Let me know if there’s something I’m missing! Thanks for your help.

Best

Oskar

**Comment by njohner** [comment]
Hi Oskar,

Thanks for the feedback. To your first point, I just tested and for me the download works with `ftp`, I did get a `connection refused` once, but when I tried again it worked. I've repeated the process a few times now and it always works. So I think that might have been a temporary issue on the ebi side.

To your second point:
- `--amr` is only used by `zdb run`, not by `zdb setup`, because there is no need to setup a reference database for AMRs, as the database is included in the software used (AMRFInderPlus). I think it's correctly documented in the help (try `zdb setup --help` and you should see no mention of `--amr`) as well as in the README (see https://github.com/metagenlab/zDB?tab=readme-ov-file#setting-up-the-reference-databases)
- `--dir` on the other hand should work. I tested right now and it works fine for me. The way to specify these arguments is maybe unusual and might have been the issue, you need to use an `=` between the argument and its value, so e.g. `zdb setup --dir=test --pfam`.

I hope that helps, if not let me know.

**Comment by ohickl** [comment]
True, my bad! Didnt read properly.
Thanks Niklaus
PS
I have another issue completing a run, ill make a new issue
